In [1]:
import pandas as pd
from pathlib import Path

In [2]:
LOAD_PATH = Path("../../data/combined")

In [3]:
sold = pd.read_parquet(LOAD_PATH/"sold_fe.parquet")

In [4]:
def print_IQR(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    

    print(column,"---------")
    print("Q1: ", Q1)
    print("Q3: ", Q3)
    print("IQR: ", IQR)
    print("lower: ", lower)
    print("upper: ", upper)
    print(df[column].describe(percentiles=[.01,.05,.1,0.9,0.95,0.99,0.995,0.999]))
    print()

In [5]:
def percentile_columns(df, column, percentile):
    return df[column].quantile(percentile)

In [26]:
sold.columns

Index(['OriginalListPrice', 'CloseDate', 'ClosePrice', 'Latitude', 'Longitude',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'AssociationFeeFrequency',
       'CountyOrParish', 'ParkingTotal', 'PropertySubType', 'YearBuilt',
       'BathroomsTotalInteger', 'City', 'BedroomsTotal', 'StateOrProvince',
       'FireplaceYN', 'Levels', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'PostalCode', 'AssociationFee',
       'PurchaseContractDate', 'ListingContractDate',
       'ContractStatusChangeDate', 'rate_30yr_fixed', 'ViewYN',
       'PoolPrivateYN', 'MLSAreaMajor', 'ListOfficeName', 'BuyerOfficeName',
       'listing_after_close_flag', 'purchase_after_close_flag',
       'geographic_error', 'PriceRatio', 'PricePerSqFt', 'Year', 'Month',
       'YrMo', 'ListingToContractDays', 'ContractToCloseDays'],
      dtype='str')

In [6]:
print_IQR(sold,"ClosePrice")

ClosePrice ---------
Q1:  598000.0
Q3:  1325000.0
IQR:  727000.0
lower:  -492500.0
upper:  2415500.0
count    3.855680e+05
mean     1.214240e+06
std      6.169983e+06
min      1.150000e+00
1%       2.400000e+05
5%       3.675000e+05
10%      4.390000e+05
90%      2.100000e+06
95%      2.900000e+06
99%      5.600000e+06
99.5%    7.500000e+06
99.9%    1.512587e+07
max      9.895000e+08
Name: ClosePrice, dtype: float64

In [7]:
sold.describe().T

C:\Users\alext\miniconda3\envs\da-intern\Lib\site-packages\pandas\core\nanops.py:1027: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,count,mean,min,25%,50%,75%,max,std
OriginalListPrice,384866.0,1242861.235795,0.0,599900.0,849000.0,1320000.0,1390000000.0,6472260.947725
CloseDate,385570,2025-02-22 16:54:55.899577,2024-01-01 00:00:00,2024-07-22 00:00:00,2025-02-25 00:00:00,2025-09-18 00:00:00,2026-04-30 00:00:00,NaN
ClosePrice,385568.0,1214240.219467,1.15,598000.0,840000.0,1325000.0,989500000.0,6169982.645598
Latitude,370406.0,34.630412,-117.472493,33.725191,34.033737,34.526496,50.0,1.69704
Longitude,370406.0,-118.559681,-177.646696,-118.850321,-117.993549,-117.265399,329.0,2.944774
LivingArea,385426.0,1941.829324,1.0,1280.0,1675.0,2256.0,17021321.0,27431.787763
ListPrice,385570.0,1162617.286379,695.0,599000.0,839000.0,1299000.0,75000000.0,1301357.232574
DaysOnMarket,385570.0,36.416285,0.0,8.0,18.0,47.0,2177.0,48.369528
ParkingTotal,385145.0,9.736503,0.25,2.0,2.0,3.0,2593669.0,4179.455838
YearBuilt,385331.0,1979.835204,1776.0,1962.0,1980.0,2000.0,2026.0,25.659339
BathroomsTotalInteger,385515.0,2.576919,1.0,2.0,2.0,3.0,175.0,1.122558
BedroomsTotal,385570.0,3.242825,1.0,3.0,3.0,4.0,45.0,1.035752
LotSizeArea,354824.0,31620.79093,0.0,5023.0,7035.0,10821.0,418727400.0,1142599.275654
MainLevelBedrooms,223079.0,2.04693,0.0,1.0,2.0,3.0,3333.0,7.346212
GarageSpaces,371510.0,1.974709,0.0,2.0,2.0,2.0,600.0,3.756883
AssociationFee,296977.0,235.087049,0.0,0.0,105.0,369.0,750000.0,1795.019303
PurchaseContractDate,385396,2025-01-22 08:08:44.518158,1923-11-16 00:00:00,2024-06-19 00:00:00,2025-01-26 00:00:00,2025-08-18 00:00:00,2026-04-30 00:00:00,NaN
ListingContractDate,385569,2024-12-09 01:36:30.116944,1984-08-28 00:00:00,2024-05-15 00:00:00,2024-12-02 00:00:00,2025-06-27 00:00:00,2026-05-01 00:00:00,NaN
ContractStatusChangeDate,384985,2025-02-23 07:50:18.217333,2024-01-01 00:00:00,2024-07-23 00:00:00,2025-02-25 00:00:00,2025-09-18 00:00:00,2026-04-30 00:00:00,NaN
rate_30yr_fixed,385570.0,6.601828,6.0475,6.332,6.715,6.82,7.06,0.293489
PriceRatio,384864.0,inf,0.000001,0.955414,0.997749,1.020068,inf,NaN
PricePerSqFt,385424.0,646.528071,0.000498,372.781065,541.176471,735.070341,1164066.852368,4848.605628
Year,385570.0,2024.681319,2024.0,2024.0,2025.0,2025.0,2026.0,0.692673
Month,385570.0,6.095765,1.0,3.0,6.0,9.0,12.0,3.361499
ListingToContractDays,385395.0,44.236651,-36407.0,10.0,24.0,57.0,14657.0,87.53469
ContractToCloseDays,385396.0,31.396784,-331.0,21.0,28.0,36.0,36629.0,64.117212

In [8]:
# More obvious outliers
outliers = [
    'GarageSpaces',
    'MainLevelBedrooms',
    'BedroomsTotal',
    'BathroomsTotalInteger',
    'ParkingTotal'
]
for out in outliers:
    print_IQR(sold, out)

GarageSpaces ---------
Q1:  2.0
Q3:  2.0
IQR:  0.0
lower:  2.0
upper:  2.0
count    371510.000000
mean          1.974709
std           3.756883
min           0.000000
1%            0.000000
5%            0.000000
10%           1.000000
90%           3.000000
95%           3.000000
99%           4.000000
99.5%         5.000000
99.9%         9.000000
max         600.000000
Name: GarageSpaces, dtype: float64

MainLevelBedrooms ---------
Q1:  1
Q3:  3
IQR:  2
lower:  -2.0
upper:  6.0
count    223079.0
mean      2.04693
std      7.346212
min           0.0
1%            0.0
5%            0.0
10%           0.0
90%           4.0
95%           4.0
99%           5.0
99.5%         5.0
99.9%         7.0
max        3333.0
Name: MainLevelBedrooms, dtype: Float64

BedroomsTotal ---------
Q1:  3.0
Q3:  4.0
IQR:  1.0
lower:  1.5
upper:  5.5
count    385570.0
mean     3.242825
std      1.035752
min           1.0
1%            1.0
5%            2.0
10%           2.0
90%           4.0
95%           5.0
99%           6.0
99.5%         6.0
99.9%         8.0
max          45.0
Name: BedroomsTotal, dtype: Float64

BathroomsTotalInteger ---------
Q1:  2
Q3:  3
IQR:  1
lower:  0.5
upper:  4.5
count    385515.0
mean     2.576919
std      1.122558
min           1.0
1%            1.0
5%            1.0
10%           2.0
90%           4.0
95%           4.0
99%           6.0
99.5%         7.0
99.9%         9.0
max         175.0
Name: BathroomsTotalInteger, dtype: Float64

ParkingTotal ---------
Q1:  2.0
Q3:  3.0
IQR:  1.0
lower:  0.5
upper:  4.5
count    3.851450e+05
mean     9.736503e+00
std      4.179456e+03
min      2.500000e-01
1%       1.000000e+00
5%       1.000000e+00
10%      1.000000e+00
90%      4.000000e+00
95%      6.000000e+00
99%      1.000000e+01
99.5%    1.300000e+01
99.9%    3.000000e+01
max      2.593669e+06
Name: ParkingTotal, dtype: float64

Looking at the IQR and percentages,

GarageSpaces, MainLevelBedrooms, BedroomsTotal, BathroomsTotalInteger, ParkingTotal numbers make a lot of sense at the 99th percentile. For these columns, everything after the 99th percentile will be removed

In [9]:
sold.describe().T

C:\Users\alext\miniconda3\envs\da-intern\Lib\site-packages\pandas\core\nanops.py:1027: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,count,mean,min,25%,50%,75%,max,std
OriginalListPrice,384866.0,1242861.235795,0.0,599900.0,849000.0,1320000.0,1390000000.0,6472260.947725
CloseDate,385570,2025-02-22 16:54:55.899577,2024-01-01 00:00:00,2024-07-22 00:00:00,2025-02-25 00:00:00,2025-09-18 00:00:00,2026-04-30 00:00:00,NaN
ClosePrice,385568.0,1214240.219467,1.15,598000.0,840000.0,1325000.0,989500000.0,6169982.645598
Latitude,370406.0,34.630412,-117.472493,33.725191,34.033737,34.526496,50.0,1.69704
Longitude,370406.0,-118.559681,-177.646696,-118.850321,-117.993549,-117.265399,329.0,2.944774
LivingArea,385426.0,1941.829324,1.0,1280.0,1675.0,2256.0,17021321.0,27431.787763
ListPrice,385570.0,1162617.286379,695.0,599000.0,839000.0,1299000.0,75000000.0,1301357.232574
DaysOnMarket,385570.0,36.416285,0.0,8.0,18.0,47.0,2177.0,48.369528
ParkingTotal,385145.0,9.736503,0.25,2.0,2.0,3.0,2593669.0,4179.455838
YearBuilt,385331.0,1979.835204,1776.0,1962.0,1980.0,2000.0,2026.0,25.659339
BathroomsTotalInteger,385515.0,2.576919,1.0,2.0,2.0,3.0,175.0,1.122558
BedroomsTotal,385570.0,3.242825,1.0,3.0,3.0,4.0,45.0,1.035752
LotSizeArea,354824.0,31620.79093,0.0,5023.0,7035.0,10821.0,418727400.0,1142599.275654
MainLevelBedrooms,223079.0,2.04693,0.0,1.0,2.0,3.0,3333.0,7.346212
GarageSpaces,371510.0,1.974709,0.0,2.0,2.0,2.0,600.0,3.756883
AssociationFee,296977.0,235.087049,0.0,0.0,105.0,369.0,750000.0,1795.019303
PurchaseContractDate,385396,2025-01-22 08:08:44.518158,1923-11-16 00:00:00,2024-06-19 00:00:00,2025-01-26 00:00:00,2025-08-18 00:00:00,2026-04-30 00:00:00,NaN
ListingContractDate,385569,2024-12-09 01:36:30.116944,1984-08-28 00:00:00,2024-05-15 00:00:00,2024-12-02 00:00:00,2025-06-27 00:00:00,2026-05-01 00:00:00,NaN
ContractStatusChangeDate,384985,2025-02-23 07:50:18.217333,2024-01-01 00:00:00,2024-07-23 00:00:00,2025-02-25 00:00:00,2025-09-18 00:00:00,2026-04-30 00:00:00,NaN
rate_30yr_fixed,385570.0,6.601828,6.0475,6.332,6.715,6.82,7.06,0.293489
PriceRatio,384864.0,inf,0.000001,0.955414,0.997749,1.020068,inf,NaN
PricePerSqFt,385424.0,646.528071,0.000498,372.781065,541.176471,735.070341,1164066.852368,4848.605628
Year,385570.0,2024.681319,2024.0,2024.0,2025.0,2025.0,2026.0,0.692673
Month,385570.0,6.095765,1.0,3.0,6.0,9.0,12.0,3.361499
ListingToContractDays,385395.0,44.236651,-36407.0,10.0,24.0,57.0,14657.0,87.53469
ContractToCloseDays,385396.0,31.396784,-331.0,21.0,28.0,36.0,36629.0,64.117212

In [10]:
outliers = [
    'LotSizeArea',
    'AssociationFee',
    'LivingArea'
]
for out in outliers:
    print_IQR(sold, out)

LotSizeArea ---------
Q1:  5023.0
Q3:  10821.0
IQR:  5798.0
lower:  -3674.0
upper:  19518.0
count    3.548240e+05
mean     3.162079e+04
std      1.142599e+06
min      0.000000e+00
1%       0.000000e+00
5%       9.893000e+00
10%      1.975000e+03
90%      3.401340e+04
95%      9.452285e+04
99%      3.802751e+05
99.5%    5.326910e+05
99.9%    1.270160e+06
max      4.187274e+08
Name: LotSizeArea, dtype: float64

AssociationFee ---------
Q1:  0.0
Q3:  369.0
IQR:  369.0
lower:  -553.5
upper:  922.5
count    296977.000000
mean        235.087049
std        1795.019303
min           0.000000
1%            0.000000
5%            0.000000
10%           0.000000
90%         579.988000
95%         750.000000
99%        1552.000000
99.5%      2091.000000
99.9%      4300.024000
max      750000.000000
Name: AssociationFee, dtype: float64

LivingArea ---------
Q1:  1280.0
Q3:  2256.0
IQR:  976.0
lower:  -184.0
upper:  3720.0
count    3.854260e+05
mean     1.941829e+03
std      2.743179e+04
min      1.000000e+00
1%       6.620000e+02
5%       8.810000e+02
10%      1.019000e+03
90%      3.012000e+03
95%      3.599750e+03
99%      5.314750e+03
99.5%    6.283000e+03
99.9%    9.382150e+03
max      1.702132e+07
Name: LivingArea, dtype: float64

In [11]:
outliers = [
    'ClosePrice'
]
for out in outliers:
    print_IQR(sold, out)

ClosePrice ---------
Q1:  598000.0
Q3:  1325000.0
IQR:  727000.0
lower:  -492500.0
upper:  2415500.0
count    3.855680e+05
mean     1.214240e+06
std      6.169983e+06
min      1.150000e+00
1%       2.400000e+05
5%       3.675000e+05
10%      4.390000e+05
90%      2.100000e+06
95%      2.900000e+06
99%      5.600000e+06
99.5%    7.500000e+06
99.9%    1.512587e+07
max      9.895000e+08
Name: ClosePrice, dtype: float64

In [16]:
outlier_sold = sold.copy()
outlier_sold["Flagged"] = False

condition = outlier_sold["GarageSpaces"].gt(percentile_columns(outlier_sold,"GarageSpaces",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["MainLevelBedrooms"].gt(percentile_columns(outlier_sold,"MainLevelBedrooms",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["BedroomsTotal"].gt(percentile_columns(outlier_sold,"BedroomsTotal",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["BathroomsTotalInteger"].gt(percentile_columns(outlier_sold,"BathroomsTotalInteger",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["ParkingTotal"].gt(percentile_columns(outlier_sold,"ParkingTotal",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition

condition = outlier_sold["LotSizeArea"].gt(percentile_columns(outlier_sold,"LotSizeArea",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["AssociationFee"].gt(percentile_columns(outlier_sold,"AssociationFee",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["LivingArea"].gt(percentile_columns(outlier_sold,"LivingArea",.999)).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition

condition = outlier_sold["ClosePrice"].le(0).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition
condition = outlier_sold["ClosePrice"].gt(2415500.0).fillna(False)
outlier_sold["Flagged"] = outlier_sold["Flagged"] | condition

print(outlier_sold[outlier_sold["Flagged"]].shape[0]/ outlier_sold.shape[0])

0.0772388930674067

In [18]:
sold_removed = outlier_sold.copy()

sold_removed = sold_removed.drop(sold_removed[sold_removed['Flagged']==True].index)

In [19]:
sold_removed.shape

(355789, 45)

In [20]:
columns = [
    'GarageSpaces',
    'MainLevelBedrooms',
    'BedroomsTotal',
    'BathroomsTotalInteger',
    'ParkingTotal',
    'LotSizeArea',
    'AssociationFee',
    'LivingArea',
    'ClosePrice'
]

In [25]:
sold_removed[columns].describe().T

,count,mean,std,min,25%,50%,75%,max
GarageSpaces,344530.0,1.896083,0.777026,0.0,2.0,2.0,2.0,9.0
MainLevelBedrooms,212224.0,2.023607,1.383152,0.0,1.0,2.0,3.0,7.0
BedroomsTotal,355789.0,3.160157,0.973085,1.0,3.0,3.0,4.0,8.0
BathroomsTotalInteger,355740.0,2.43918,0.850469,1.0,2.0,2.0,3.0,9.0
ParkingTotal,355373.0,2.587859,1.748928,0.25,2.0,2.0,3.0,30.0
LotSizeArea,326037.0,22174.655537,69204.563668,0.0,5000.0,6970.0,10223.0,1268032.0
AssociationFee,281307.0,215.983141,307.102356,0.0,0.0,100.0,365.0,4295.0
LivingArea,355739.0,1759.871401,714.777769,1.0,1250.0,1617.0,2119.0,9288.0
ClosePrice,355787.0,923264.716678,472393.913598,1.15,577227.0,800000.0,1185000.0,2415500.0

In [23]:
sold_removed.shape

(355789, 45)

In [24]:
sold_removed[columns].describe()

,GarageSpaces,MainLevelBedrooms,BedroomsTotal,BathroomsTotalInteger,ParkingTotal,LotSizeArea,AssociationFee,LivingArea,ClosePrice
count,344530.000000,212224.0,355789.0,355740.0,355373.000000,3.260370e+05,281307.000000,355739.000000,3.557870e+05
mean,1.896083,2.023607,3.160157,2.43918,2.587859,2.217466e+04,215.983141,1759.871401,9.232647e+05
std,0.777026,1.383152,0.973085,0.850469,1.748928,6.920456e+04,307.102356,714.777769,4.723939e+05
min,0.000000,0.0,1.0,1.0,0.250000,0.000000e+00,0.000000,1.000000,1.150000e+00
25%,2.000000,1.0,3.0,2.0,2.000000,5.000000e+03,0.000000,1250.000000,5.772270e+05
50%,2.000000,2.0,3.0,2.0,2.000000,6.970000e+03,100.000000,1617.000000,8.000000e+05
75%,2.000000,3.0,4.0,3.0,3.000000,1.022300e+04,365.000000,2119.000000,1.185000e+06
max,9.000000,7.0,8.0,9.0,30.000000,1.268032e+06,4295.000000,9288.000000,2.415500e+06

In [28]:
sold_removed.to_parquet(LOAD_PATH/"sold_outliers_removed.parquet")