In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import datetime as dt

In [2]:
def print_missing_data(df):
        
    # percent missing data per column
    missing_count = df.isnull().sum()
    percent_missing = round(missing_count * 100 / len(df), 2)
    missing_value_df = pd.DataFrame(
        {
            'missing_count': missing_count,
            'percent_missing': percent_missing
        }
    )
    missing_value_df.sort_values('percent_missing', inplace=True)
    return missing_value_df

In [3]:
save_path = Path("../../data/combined")

In [4]:
sold = pd.read_csv(save_path/"sold_fred.csv")

C:\Users\alext\AppData\Local\Temp\ipykernel_11236\840303522.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: ListAgentEmail, 3: FireplaceYN, 4: OriginatingSystemName, 5: OriginatingSystemSubName, 6: BuyerAgencyCompensationType, 7: latfilled, 8: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv(save_path/"sold_fred.csv")

In [5]:
sold.shape

(414184, 86)

In [6]:
sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled', 'year_month', 'rate_30yr_fixed'],
      dtype='str')

In [7]:
market_analysis_fields = ['OriginalListPrice'
,'CloseDate'
,'ClosePrice'
,'Latitude'
,'Longitude'
,'PropertyType'
,'LivingArea'
,'ListPrice'
,'DaysOnMarket'
,'FireplacesTotal'
,'AssociationFeeFrequency'
,'AboveGradeFinishedArea'
,'TaxAnnualAmount'
,'CountyOrParish'
,'ElementarySchool'
,'ParkingTotal'
,'PropertySubType'
,'LotSizeAcres'
,'YearBuilt'
,'BathroomsTotalInteger'
,'City'
,'BuildingAreaTotal'
,'BedroomsTotal'
,'BelowGradeFinishedArea'
,'StateOrProvince'
,'CoveredSpaces'
,'FireplaceYN'
,'Stories'
,'HighSchool'
,'Levels'
,'LotSizeDimensions'
,'LotSizeArea'
,'MainLevelBedrooms'
,'NewConstructionYN'
,'GarageSpaces'
,'PostalCode'
,'AssociationFee'
,'LotSizeSquareFeet'
,'PurchaseContractDate'
,'ListingContractDate'
,'ContractStatusChangeDate'
,'MiddleOrJuniorSchoolDistrict'
,'rate_30yr_fixed'
,'BasementYN'
,'WaterfrontYN'
,'ViewYN'
,'PoolPrivateYN'
,'MLSAreaMajor'
,'ListOfficeName',
'BuyerOfficeName']

In [8]:
# Filter by Market Analysis Fields
market_analysis_filter_sold = sold[market_analysis_fields]

In [9]:
market_analysis_filter_sold.columns

Index(['OriginalListPrice', 'CloseDate', 'ClosePrice', 'Latitude', 'Longitude',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'TaxAnnualAmount', 'CountyOrParish', 'ElementarySchool', 'ParkingTotal',
       'PropertySubType', 'LotSizeAcres', 'YearBuilt', 'BathroomsTotalInteger',
       'City', 'BuildingAreaTotal', 'BedroomsTotal', 'BelowGradeFinishedArea',
       'StateOrProvince', 'CoveredSpaces', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'LotSizeDimensions', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'PurchaseContractDate',
       'ListingContractDate', 'ContractStatusChangeDate',
       'MiddleOrJuniorSchoolDistrict', 'rate_30yr_fixed', 'BasementYN',
       'WaterfrontYN', 'ViewYN', 'PoolPrivateYN', 'MLSAreaMajor',
       'ListOfficeName', 'BuyerOfficeName'],
      dtype='str')

In [10]:
print_missing_data(market_analysis_filter_sold)

                              missing_count  percent_missing
CloseDate                                 0             0.00
ClosePrice                                2             0.00
ListPrice                                 0             0.00
PropertyType                              0             0.00
CountyOrParish                            0             0.00
DaysOnMarket                              0             0.00
StateOrProvince                           0             0.00
BedroomsTotal                            11             0.00
ListOfficeName                            0             0.00
rate_30yr_fixed                           0             0.00
ListingContractDate                       1             0.00
PostalCode                                2             0.00
BathroomsTotalInteger                    69             0.02
PurchaseContractDate                    195             0.05
LivingArea                              234             0.06
City                                    311             0.08
FireplaceYN                             331             0.08
YearBuilt                               372             0.09
ParkingTotal                            426             0.10
ContractStatusChangeDate                589             0.14
OriginalListPrice                       759             0.18
PropertySubType                         804             0.19
BuyerOfficeName                        6743             1.63
Latitude                              15956             3.85
Longitude                             15956             3.85
GarageSpaces                          17778             4.29
NewConstructionYN                     30748             7.42
LotSizeArea                           32033             7.73
LotSizeSquareFeet                     32162             7.77
LotSizeAcres                          32564             7.86
ViewYN                                35276             8.52
PoolPrivateYN                         35674             8.61
Levels                                39925             9.64
MLSAreaMajor                          55385            13.37
Stories                               63812            15.41
AssociationFee                        94748            22.88
MainLevelBedrooms                    173885            41.98
AssociationFeeFrequency              241610            58.33
HighSchool                           342115            82.60
ElementarySchool                     359067            86.69
BuildingAreaTotal                    385160            92.99
LotSizeDimensions                    394062            95.14
BasementYN                           406080            98.04
BelowGradeFinishedArea               411781            99.42
WaterfrontYN                         413925            99.94
FireplacesTotal                      414184           100.00
AboveGradeFinishedArea               414184           100.00
TaxAnnualAmount                      414184           100.00
CoveredSpaces                        414184           100.00
MiddleOrJuniorSchoolDistrict         414184           100.00

In [11]:
# drop columns

null_90_columns = [
    'MiddleOrJuniorSchoolDistrict',
    'CoveredSpaces',
    'TaxAnnualAmount',
    'FireplacesTotal',
    'AboveGradeFinishedArea',
    'BelowGradeFinishedArea',
    'LotSizeDimensions',
    'BuildingAreaTotal',
    'WaterfrontYN',
    'BasementYN',
    # I originally wanted to keep these to check for nearby schools. but there is too many missing data to check for t-tests
    'HighSchool',
    'ElementarySchool',
]
dup_columns = [
    'LotSizeAcres', 
    'LotSizeSquareFeet', # There is LotSizeArea which is the same as 'feet' and it has less missing data
    'Stories', # Stories(float) and Levels(category) are the same. Stories will be null if levels is more than 2 stories high
    'PropertyType', # We already filtered by 'Residential' 
]

In [12]:
# Filter by dropping above 90% null rate
null_90_filter = market_analysis_filter_sold.drop(columns=null_90_columns)
null_90_filter = null_90_filter.drop(columns=dup_columns)

In [13]:
null_90_filter.columns

Index(['OriginalListPrice', 'CloseDate', 'ClosePrice', 'Latitude', 'Longitude',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'AssociationFeeFrequency',
       'CountyOrParish', 'ParkingTotal', 'PropertySubType', 'YearBuilt',
       'BathroomsTotalInteger', 'City', 'BedroomsTotal', 'StateOrProvince',
       'FireplaceYN', 'Levels', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'PostalCode', 'AssociationFee',
       'PurchaseContractDate', 'ListingContractDate',
       'ContractStatusChangeDate', 'rate_30yr_fixed', 'ViewYN',
       'PoolPrivateYN', 'MLSAreaMajor', 'ListOfficeName', 'BuyerOfficeName'],
      dtype='str')

In [14]:
null_90_filter.dtypes

OriginalListPrice           float64
CloseDate                       str
ClosePrice                  float64
Latitude                    float64
Longitude                   float64
LivingArea                  float64
ListPrice                   float64
DaysOnMarket                  int64
AssociationFeeFrequency         str
CountyOrParish                  str
ParkingTotal                float64
PropertySubType                 str
YearBuilt                   float64
BathroomsTotalInteger       float64
City                            str
BedroomsTotal               float64
StateOrProvince                 str
FireplaceYN                  object
Levels                          str
LotSizeArea                 float64
MainLevelBedrooms           float64
NewConstructionYN            object
GarageSpaces                float64
PostalCode                      str
AssociationFee              float64
PurchaseContractDate            str
ListingContractDate             str
ContractStatusChangeDate        str
rate_30yr_fixed             float64
ViewYN                       object
PoolPrivateYN                object
MLSAreaMajor                    str
ListOfficeName                  str
BuyerOfficeName                 str
dtype: object

In [15]:
# Datetime Change
null_90_filter['CloseDate'] = pd.to_datetime(null_90_filter['CloseDate'])
null_90_filter['PurchaseContractDate'] = pd.to_datetime(null_90_filter['PurchaseContractDate'])
null_90_filter['ListingContractDate'] = pd.to_datetime(null_90_filter['ListingContractDate'])
null_90_filter['ContractStatusChangeDate'] = pd.to_datetime(null_90_filter['ContractStatusChangeDate'])

# Int change
int_cols = ['YearBuilt','BathroomsTotalInteger','BedroomsTotal', 'MainLevelBedrooms']
null_90_filter[int_cols] = null_90_filter[int_cols].astype('Int64')

# Bool change
bool_cols = ['FireplaceYN','NewConstructionYN', 'ViewYN', 'PoolPrivateYN']
null_90_filter[bool_cols] = null_90_filter[bool_cols].astype(bool)

In [16]:
null_90_filter.dtypes

OriginalListPrice                  float64
CloseDate                   datetime64[us]
ClosePrice                         float64
Latitude                           float64
Longitude                          float64
LivingArea                         float64
ListPrice                          float64
DaysOnMarket                         int64
AssociationFeeFrequency                str
CountyOrParish                         str
ParkingTotal                       float64
PropertySubType                        str
YearBuilt                            Int64
BathroomsTotalInteger                Int64
City                                   str
BedroomsTotal                        Int64
StateOrProvince                        str
FireplaceYN                           bool
Levels                                 str
LotSizeArea                        float64
MainLevelBedrooms                    Int64
NewConstructionYN                     bool
GarageSpaces                       float64
PostalCode                             str
AssociationFee                     float64
PurchaseContractDate        datetime64[us]
ListingContractDate         datetime64[us]
ContractStatusChangeDate    datetime64[us]
rate_30yr_fixed                    float64
ViewYN                                bool
PoolPrivateYN                         bool
MLSAreaMajor                           str
ListOfficeName                         str
BuyerOfficeName                        str
dtype: object

In [17]:
# Check date consistency
null_90_filter['listing_after_close_flag'] = (null_90_filter['CloseDate'] - null_90_filter['ListingContractDate']< dt.timedelta(days=0))
null_90_filter['purchase_after_close_flag'] = (null_90_filter['CloseDate'] - null_90_filter['PurchaseContractDate']< dt.timedelta(days=0))
null_90_filter['geographic_error'] = (
    (null_90_filter["Longitude"]==0) |
    (null_90_filter["Latitude"]==0) |
    (null_90_filter["Longitude"]>0) |
    (null_90_filter["Longitude"].isna()) |
    (null_90_filter["Latitude"].isna()) 
)

In [18]:
print_missing_data(null_90_filter)

                           missing_count  percent_missing
CloseDate                              0             0.00
ClosePrice                             2             0.00
ListPrice                              0             0.00
DaysOnMarket                           0             0.00
BedroomsTotal                         11             0.00
CountyOrParish                         0             0.00
FireplaceYN                            0             0.00
StateOrProvince                        0             0.00
ListingContractDate                    1             0.00
PoolPrivateYN                          0             0.00
ViewYN                                 0             0.00
rate_30yr_fixed                        0             0.00
NewConstructionYN                      0             0.00
PostalCode                             2             0.00
listing_after_close_flag               0             0.00
ListOfficeName                         0             0.00
geographic_error                       0             0.00
purchase_after_close_flag              0             0.00
BathroomsTotalInteger                 69             0.02
PurchaseContractDate                 195             0.05
LivingArea                           234             0.06
City                                 311             0.08
YearBuilt                            372             0.09
ParkingTotal                         426             0.10
ContractStatusChangeDate             589             0.14
OriginalListPrice                    759             0.18
PropertySubType                      804             0.19
BuyerOfficeName                     6743             1.63
Longitude                          15956             3.85
Latitude                           15956             3.85
GarageSpaces                       17778             4.29
LotSizeArea                        32033             7.73
Levels                             39925             9.64
MLSAreaMajor                       55385            13.37
AssociationFee                     94748            22.88
MainLevelBedrooms                 173885            41.98
AssociationFeeFrequency           241610            58.33

In [19]:
# Drops rows

# negative
negative_filter = null_90_filter.drop(null_90_filter[null_90_filter['DaysOnMarket'] < 0].index)
negative_filter = negative_filter.drop(negative_filter[negative_filter['LivingArea'] <= 0].index)
negative_filter = negative_filter.drop(negative_filter[negative_filter['ClosePrice'] <= 0].index)
negative_filter = negative_filter.drop(negative_filter[negative_filter['BedroomsTotal'] <= 0].index)
negative_filter = negative_filter.drop(negative_filter[negative_filter['BathroomsTotalInteger'] <= 0].index)
negative_filter = negative_filter.drop(negative_filter[negative_filter['ParkingTotal'] <= 0].index)

# inconsistent
inconsistent_filter = negative_filter.drop(negative_filter[negative_filter['PostalCode']=="0"].index) # cannot be 0
inconsistent_filter = inconsistent_filter.drop(inconsistent_filter[inconsistent_filter['StateOrProvince']!="CA"].index) # outside of CA

# null 
# null_filter = inconsistent_filter.drop(inconsistent_filter[inconsistent_filter['PostalCode'].isna()].index) # postalcode nulls

In [20]:
# test = null_filter[null_filter["OriginalListPrice"].notna()]
# test["listDiff"] = np.isclose(test['ListPrice'], test['OriginalListPrice'])
# (test['ListPrice'] == test['OriginalListPrice']).mean()

# # Since about 80% stay the same from original to list, i decided to fill in the missing originallistprice with listprice since there is only 0.14% data from OriginalListPrice

In [21]:
# # Data Impution
# imputation_df = invalid_numeric_filter
# imputation_cols = ['ParkingTotal', 'BathroomsTotalInteger']

# imputation_df['OriginalListPrice'] = imputation_df['OriginalListPrice'].fillna(imputation_df['ListPrice'])
# imputation_df[imputation_cols] = imputation_df[imputation_cols].fillna(imputation_df[imputation_cols].median())

In [22]:
path = Path("../../data/combined/done_week_45")
inconsistent_filter.to_parquet(path/"sold.parquet", index=False)